import Head from 'next/head';
import Navbar from '../../components/Navbar';
import Hero from '../../components/Hero';
import Categories from '../../components/Categories';
import Benefits from '../../components/Benefits';
import AboutUs from '../../components/AboutUs';
import Comfort from '../../components/Comfort';
import Brands from '../../components/Brands';
import PostItem from '../../components/PostItem';
import Footer from '../../components/Footer';

import posts from '@/assets/posts';

export default function Home() {

  return (
    <>
      <Head>
        <title>Workout: Sport Clothes Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <header>
          <Navbar />
        </header>
        <main>
          <Hero />
          <Categories />
          <Benefits />
          <AboutUs />
          <Comfort />
          <Brands />
          <PostItem posts={posts} />
        </main>
        <footer>
          <Footer />
        </footer>
      </>
    </>
  );
}
