import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'
import Categories from '../../components/Categories'
import Benefits from '../../components/Benefits'
import Footer from '../../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Workout: Sport Clothes Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <Hero/>
        <Categories />
        <Benefits/>
        <Footer/>
      </>

    </>
  )
}
